name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: ubuntu-latest
            arch: x86_64
            rust_target: x86_64-unknown-linux-gnu
          - os: macos-latest
            arch: x86_64
            rust_target: x86_64-apple-darwin
          - os: macos-latest
            arch: aarch64
            rust_target: aarch64-apple-darwin
          - os: windows-latest
            arch: x86_64
            rust_target: x86_64-pc-windows-msvc
    runs-on: ${{ matrix.config.os }}

    steps:
    - uses: actions/checkout@v4

    - name: install dependencies (mac x86_64 only)
      if: matrix.config.os == 'macos-latest' && matrix.config.arch == 'x86_64'
      run: |
        rustup show
        rustup target add x86_64-apple-darwin

    - name: Build (mac x86_64 only)
      if: matrix.config.os == 'macos-latest' && matrix.config.arch == 'x86_64'
      run: |
        cargo build --target x86_64-apple-darwin --verbose
        cp target/x86_64-apple-darwin/debug/hirs hirs-${{ matrix.config.rust_target }}

    - name: Build (mac aarch64 only)
      if: matrix.config.os == 'macos-latest' && matrix.config.arch == 'aarch64'
      run: |
        cargo build --verbose
        cp target/debug/hirs hirs-${{ matrix.config.rust_target }}
        
    - name: Build
      if: matrix.config.os != 'macos-latest'
      run: |
        cargo build --verbose
        cp target/debug/hirs hirs-${{ matrix.config.rust_target }}

    - name: Run tests (mac x86_64 only)
      if: matrix.config.os == 'macos-latest' && matrix.config.arch == 'x86_64'
      run: cargo test --target x86_64-apple-darwin --verbose
    
    - name: Run tests (mac aarch64 only)
      if: matrix.config.os == 'macos-latest' && matrix.config.arch == 'aarch64'
      run: cargo test --verbose
      
    - name: Run tests
      if: matrix.config.os != 'macos-latest'
      run: cargo test --verbose

    - name: Run (mac x86_64 only)
      if: matrix.config.os == 'macos-latest' && matrix.config.arch == 'x86_64'
      run: cargo run --target x86_64-apple-darwin
      
    - name: Run (mac aarch64 only)
      if: matrix.config.os == 'macos-latest' && matrix.config.arch == 'aarch64'
      run: cargo run

    - name: Run
      if: matrix.config.os != 'macos-latest'
      run: cargo run

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: hirs-${{ matrix.config.rust_target }}
        path: hirs-${{ matrix.config.rust_target }}

  pre-release:
    name: "Pre Release"
    needs: [build]
    runs-on: "ubuntu-latest"
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
    - name: Create Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          hirs-x86_64-unknown-linux-gnu/hirs-x86_64-unknown-linux-gnu
          hirs-x86_64-apple-darwin/hirs-x86_64-apple-darwin
          hirs-aarch64-apple-darwin/hirs-aarch64-apple-darwin
          hirs-x86_64-pc-windows-msvc/hirs-x86_64-pc-windows-msvc
